name: Pages
on:
  workflow_dispatch:
  workflow_call:
jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/install
  build:
    name: Build packages
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Build pages
        run: yarn build
      - name: Upload pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public/typedoc
  deploy:
    name: Deploy pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    concurrency:
      group: github-pages
      cancel-in-progress: true
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v1
