name: Prerelease
on:
  push:
    branches:
      - 'next'
jobs:
  prerelease:
    name: Prerelease packages
    runs-on: ubuntu-latest
    environment: development
    concurrency: development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Build packages
        run: yarn build
      - name: Version packages
        run: lerna version --conventional-prerelease --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish packages
        run: lerna publish from-package --dist-tag next --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
