name: Release
on:
  push:
    branches:
      - 'master'
jobs:
  release:
    name: Release packages
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Install dependencies
        uses: ./.github/actions/install
      - name: Build packages
        run: yarn build
      - name: Version packages
        run: lerna version --conventional-graduate --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish packages
        run: lerna publish from-package --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  deploy:
    name: Deploy pages
    uses: ./.github/workflows/pages.yml
