name: Release
on:
  push:
    branches:
      - "master"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: production
    concurrency: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Install
        uses: ./.github/actions/install
      - name: Build
        run: yarn build
      - name: Version
        run: lerna version --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish
        run: lerna publish from-package --yes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
