name: Release
on:
  push:
    branches:
      - 'master'
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment: production
    concurrency: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install
        uses: ./.github/actions/install
      - name: Update npm
        run: npm install -g npm@latest
      - name: Build
        run: yarn build
      - name: Version
        run: lerna version --conventional-graduate --yes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: npm publish --workspaces --provenance
